// GTEM — per-session knowledge-check questions, keyed by session id.
// Shape: { q, options: [...], answer: <index>, explain }.
// Unit I authored; further units layered in per build.

export const QUIZ = {
  "1.1": [
    { q: "Thrust from a jet engine is a direct consequence of which of Newton's laws?", options: ["First law (inertia)", "Second law (F = ma)", "Third law (action–reaction)", "Law of gravitation"], answer: 2,
      explain: "The engine accelerates air rearward; the equal and opposite reaction pushes the aircraft forward — Newton's third law." },
    { q: "In the relation F = ṁ·ΔV, thrust can be increased by…", options: ["Only increasing jet velocity", "Only increasing mass flow", "Increasing mass flow and/or the velocity change", "Reducing the air density"], answer: 2,
      explain: "Force equals mass-flow rate times the change in velocity, so raising either factor raises thrust — the basis of bigger fans vs faster jets." },
    { q: "A running engine on a static test stand produces thrust but essentially zero…", options: ["Fuel flow", "Propulsive work", "Exhaust gas", "Rotor speed"], answer: 1,
      explain: "Work = force × distance. With the aircraft stationary there is no distance travelled, so no propulsive work is done despite the thrust." },
  ],
  "1.2": [
    { q: "The continuity equation ṁ = ρAV tells us that if duct area narrows and density is roughly constant, velocity must…", options: ["Decrease", "Increase", "Stay the same", "Drop to zero"], answer: 1,
      explain: "Mass flow is conserved, so a smaller area forces a higher velocity — the principle behind nozzles and diffusers." },
    { q: "Across the combustor, pressure is held roughly constant while…", options: ["Temperature falls", "Temperature rises sharply", "Velocity drops to zero", "Density increases"], answer: 1,
      explain: "Combustion adds heat at nearly constant pressure, spiking the temperature — the Brayton constant-pressure heat addition." },
    { q: "Station pressures and temperatures (like EGT) are useful mainly because…", options: ["They set the fuel's octane", "They are random", "Each component changes them predictably, so faults show up", "They control cabin pressure"], answer: 2,
      explain: "Because each component's effect on P and T is predictable, an abnormal reading points to the responsible component — the basis of engine monitoring." },
  ],
  "1.3": [
    { q: "The defining feature of the Brayton cycle's combustion process is that it occurs at constant…", options: ["Volume", "Pressure", "Temperature", "Entropy"], answer: 1,
      explain: "Unlike the constant-volume burn of a piston engine, the gas turbine adds heat at constant pressure, enabling continuous steady flow." },
    { q: "In a gas turbine, the turbine extracts…", options: ["All of the gas energy", "Just enough energy to drive the compressor (and fan/accessories)", "No energy at all", "Only enough to spin the starter"], answer: 1,
      explain: "The turbine drives the compressor; the surplus energy left in the gas becomes thrust (jet) or shaft power (prop/shaft)." },
    { q: "On a P–V diagram of the cycle, raising the pressure ratio…", options: ["Shrinks the enclosed area", "Enlarges the enclosed area (more work) up to a temperature limit", "Has no effect on work", "Reverses the cycle"], answer: 1,
      explain: "The enclosed area is net work per cycle; higher pressure ratio enlarges it and improves thermal efficiency, limited by turbine material temperature." },
  ],
  "1.4": [
    { q: "In a high-bypass turbofan, most of the thrust is produced by…", options: ["The hot core jet", "The bypass (fan) stream of cold air", "The starter motor", "The oil system"], answer: 1,
      explain: "A modern fan can make 80%+ of thrust from the large, slow bypass stream — far more propulsively efficient than the hot core jet alone." },
    { q: "Compared with a turbofan at cruise, a pure turbojet is…", options: ["Quieter and more efficient", "Louder and less efficient at subsonic speeds", "Identical in every way", "Unable to produce thrust"], answer: 1,
      explain: "The turbojet makes thrust from a small mass of very fast gas — noisy and thirsty at subsonic cruise, where the turbofan wins." },
    { q: "Splitting compression across LP and HP spools allows…", options: ["Each spool to run near its optimum speed for stability", "The engine to run without fuel", "The removal of the turbine", "A lower fuel octane"], answer: 0,
      explain: "Concentric LP/HP shafts run at different speeds so each compressor group works near its best, improving stability across the range." },
  ],
  "1.5": [
    { q: "In a turboprop, most of the engine's energy is delivered as…", options: ["High-velocity jet thrust", "Shaft power to the propeller", "Electrical power", "Bleed air"], answer: 1,
      explain: "A power turbine and reduction gearbox drive the propeller, which does the work of moving air; the exhaust jet contributes little thrust." },
    { q: "A free (independent) power turbine is advantageous because it…", options: ["Is directly bolted to the compressor", "Decouples the load speed from the core speed", "Removes the need for fuel", "Makes the engine a turbojet"], answer: 1,
      explain: "The free turbine is coupled only aerodynamically, so the load (e.g. a rotor) can hold constant RPM while the core varies, with gentler starts." },
    { q: "Why do turboprops and turboshafts need a reduction gearbox?", options: ["To increase turbine speed", "To convert very high shaft RPM into usable propeller/rotor speed", "To store fuel", "To cool the oil"], answer: 1,
      explain: "Turbine shafts spin far too fast for a prop or rotor, so the gearbox lowers the speed and multiplies torque to a usable range." },
  ],
  "1.6": [
    { q: "Which engine type is best suited to low-speed, low-altitude regional flight?", options: ["Turbojet", "Turboprop", "Ramjet", "Low-bypass turbofan"], answer: 1,
      explain: "The propeller moves a large mass of air very efficiently below about 0.5 Mach, giving turboprops the edge on short, slow sectors." },
    { q: "Propulsive efficiency is highest when the jet velocity is…", options: ["Much higher than flight velocity", "Only slightly above flight velocity", "Exactly zero", "Equal to the speed of light"], answer: 1,
      explain: "Moving a large mass of air slowly (jet speed just above flight speed) wastes the least kinetic energy — favouring high bypass at cruise." },
    { q: "Fundamentally, all four engine types are…", options: ["Completely unrelated designs", "The same gas-generator core using its energy in different ways", "Piston engines", "Rocket motors"], answer: 1,
      explain: "Jet, fan, propeller and shaft are four ways to use the energy of one shared gas-generator core." },
  ],
  "1.7": [
    { q: "Net thrust is best expressed as…", options: ["ṁ × V_jet only", "ṁ(V_jet − V_inlet)", "V_jet ÷ V_inlet", "ṁ × fuel flow"], answer: 1,
      explain: "Net thrust = gross thrust − momentum (ram) drag = mass flow times the difference between jet and inlet velocities." },
    { q: "When a convergent nozzle chokes, an additional thrust term appears due to…", options: ["Momentum drag", "Exit pressure remaining above ambient", "The oil pump", "Reduced mass flow"], answer: 1,
      explain: "At sonic exit the nozzle can't accelerate the flow further, so exit pressure stays above ambient, adding (P_exit − P_amb)·A_exit of pressure thrust." },
    { q: "Engine thrust is physically produced as…", options: ["A single force at the nozzle", "The resultant of pressure forces on every internal surface", "Purely by the fuel pump", "Only by the compressor"], answer: 1,
      explain: "Forward and rearward pressure forces act on all components; their algebraic sum is net thrust — why worn parts can quietly rob thrust." },
  ],
  "1.8": [
    { q: "Thrust horsepower (THP) is calculated from…", options: ["Thrust alone", "Thrust × true airspeed", "Fuel flow alone", "Turbine temperature"], answer: 1,
      explain: "THP expresses useful propulsive power as thrust times speed — so a jet's 'power' rises with airspeed even at constant thrust." },
    { q: "Equivalent shaft horsepower (ESHP) is used for turboprops because it…", options: ["Ignores the propeller", "Combines shaft power with the residual jet thrust", "Measures only fuel", "Applies only to turbojets"], answer: 1,
      explain: "A turboprop makes both shaft power and a little jet thrust; ESHP adds them into one figure so it can be compared fairly." },
    { q: "Specific fuel consumption (SFC) is a good economy metric because it…", options: ["Measures only total fuel", "Normalises fuel burn against useful output (thrust or power)", "Ignores thrust entirely", "Is always the same for all engines"], answer: 1,
      explain: "SFC is fuel per unit thrust/power, so a large engine can still have excellent SFC — lower is better." },
  ],
  "1.9": [
    { q: "Overall efficiency of a jet engine equals…", options: ["Thermal efficiency + propulsive efficiency", "Thermal efficiency × propulsive efficiency", "Thermal efficiency ÷ propulsive efficiency", "Just the thermal efficiency"], answer: 1,
      explain: "The two efficiencies multiply, so both must be high — a great core matched to a poor jet still gives mediocre overall efficiency." },
    { q: "Thermal efficiency is improved mainly by raising…", options: ["Bypass ratio only", "Pressure ratio and turbine entry temperature", "Nacelle drag", "Oil pressure"], answer: 1,
      explain: "As in the Brayton cycle, higher pressure ratio and turbine temperature convert more heat into mechanical/kinetic energy." },
    { q: "The move to high-bypass turbofans primarily improved which efficiency?", options: ["Thermal", "Propulsive", "Mechanical", "Volumetric"], answer: 1,
      explain: "High bypass lifts propulsive efficiency by moving more air at lower jet velocity — the biggest gain in modern airline engines." },
  ],
  "1.10": [
    { q: "Bypass ratio is defined as the mass of…", options: ["Fuel ÷ air", "Bypass (cold) air ÷ core (hot) air", "Core air ÷ bypass air", "Air ÷ thrust"], answer: 1,
      explain: "BPR = cold bypass flow divided by hot core flow; modern airliners run 5:1 to 12:1 or higher." },
    { q: "Raising the bypass ratio generally…", options: ["Increases SFC and noise", "Lowers SFC and jet noise", "Has no effect on economy", "Requires a smaller fan"], answer: 1,
      explain: "More air moved slowly improves fuel burn and greatly reduces jet noise — at the cost of a larger, heavier nacelle." },
    { q: "Overall pressure ratio (OPR) is ultimately limited by…", options: ["Fuel colour", "Compressor-delivery and turbine-entry temperatures", "Cabin altitude", "Runway length"], answer: 1,
      explain: "Higher OPR raises thermal efficiency but is capped by the temperatures the hot-section and compressor materials can withstand." },
  ],
  "1.11": [
    { q: "The pressure high point of the whole engine occurs at…", options: ["The intake", "Compressor delivery (entry to the combustor)", "The nozzle exit", "The turbine exit"], answer: 1,
      explain: "Pressure climbs through the compressor to a peak at delivery, is held in the combustor, then falls across turbine and nozzle." },
    { q: "The hottest, most life-limiting point in the gas path is the…", options: ["Fan face", "Turbine entry temperature (just after combustion)", "Intake lip", "Nozzle exit"], answer: 1,
      explain: "Temperature peaks at turbine entry; this TET is limited by turbine material and cooling capability." },
    { q: "The nozzle's job with velocity is to…", options: ["Slow the flow to zero", "Accelerate the gas hard, converting pressure into jet velocity", "Keep velocity constant", "Reverse the flow"], answer: 1,
      explain: "The nozzle converts remaining pressure into the high jet velocity that produces thrust — a velocity-shaping device." },
  ],
  "1.12": [
    { q: "Flat rating means the engine…", options: ["Always makes maximum possible thrust", "Holds a constant certified thrust up to a corner temperature", "Cannot be used on hot days", "Has no thrust limit"], answer: 1,
      explain: "Below the corner (kink) temperature the control holds a constant thrust — dependable on cold days while protecting the hot section." },
    { q: "On a hot, high-altitude day, take-off thrust is…", options: ["Higher than standard", "Reduced, because less-dense air lowers mass flow", "Unchanged", "Infinite"], answer: 1,
      explain: "Thin, hot air reduces mass flow and thus thrust — the worst-case 'hot and high' condition for take-off performance." },
    { q: "Hard limits such as maximum EGT/TET and shaft speed exist mainly to…", options: ["Increase fuel burn", "Protect blade life and structural integrity", "Reduce thrust for fun", "Control the cabin temperature"], answer: 1,
      explain: "Exceeding these limits can damage the hot section or overspeed the rotors; ratings and flat rating keep operation safely within them." },
  ],

  "2.1": [
    { q: "The primary job of the engine inlet is to…", options: ["Accelerate air to supersonic speed", "Slow the air to a speed the compressor can accept, with minimal loss", "Burn fuel", "Extract shaft power"], answer: 1,
      explain: "The compressor needs subsonic, smooth air; the inlet diffuses and pressurises the flow with the least distortion and pressure loss." },
    { q: "A supersonic inlet differs from a subsonic one because it must first…", options: ["Add fuel", "Manage shock waves before the subsonic diffuser", "Spin the compressor", "Cool the air electrically"], answer: 1,
      explain: "Supersonic inlets decelerate the flow through controlled shocks (often with variable geometry) before the subsonic diffuser." },
    { q: "'Ram recovery' refers to…", options: ["Recovering oil from the sump", "Converting the air's velocity into a useful pressure rise", "Restarting the engine", "Reversing thrust"], answer: 1,
      explain: "As speed rises the inlet turns velocity into pressure (ram), raising delivered pressure and helping offset thrust lost with altitude." },
  ],
  "2.2": [
    { q: "A podded (nacelle) inlet is favoured on airliners because it…", options: ["Hides the compressor face", "Sits in clean air for the best pressure recovery", "Eliminates the compressor", "Adds radar stealth"], answer: 1,
      explain: "Hanging the engine in undisturbed air gives the highest pressure recovery — ideal for efficient subsonic cruise." },
    { q: "Distortion at the compressor face primarily…", options: ["Increases surge margin", "Reduces surge margin and can trigger stall", "Raises fuel octane", "Cools the turbine"], answer: 1,
      explain: "Non-uniform flow erodes surge margin and can cut thrust or cause stall — the key penalty of a poor inlet installation." },
    { q: "An S-duct is used mainly to…", options: ["Increase engine noise", "Hide the compressor face on a buried engine", "Store fuel", "Cool the exhaust"], answer: 1,
      explain: "The S-shape conceals the compressor face (for signature) at the cost of added distortion that must be managed." },
  ],
  "2.3": [
    { q: "In an axial compressor, air flows…", options: ["Radially outward", "Parallel to the shaft through many rotor/stator rows", "Backwards", "In a circle only"], answer: 1,
      explain: "Axial compressors pass air straight through alternating rotating and stationary blade rows, each adding a modest pressure rise." },
    { q: "A key advantage of the centrifugal compressor is that it…", options: ["Has very small frontal area", "Gives a large pressure rise per stage in a short, rugged package", "Needs no diffuser", "Cannot ingest debris"], answer: 1,
      explain: "One impeller stage produces a big pressure rise compactly and robustly — but its large frontal area limits it to smaller engines." },
    { q: "Large modern airliner engines use which compressor type?", options: ["Centrifugal only", "Multi-stage axial", "No compressor", "Piston compressor"], answer: 1,
      explain: "Axial compressors give the high mass flow and pressure ratio large engines need in a slim, low-drag form." },
  ],
  "2.4": [
    { q: "Inlet ice is dangerous mainly because…", options: ["It makes the engine quieter", "When shed, it can be ingested and damage the compressor", "It increases thrust", "It cools the oil"], answer: 1,
      explain: "Ice distorts the flow and, breaking off, can nick or crack compressor blades — so the front of the engine is kept ice-free." },
    { q: "The most common engine anti-ice method uses…", options: ["Electrical heating of the whole nacelle", "Hot bleed air ducted through the inlet lip", "Chemical spray", "Cooling fans"], answer: 1,
      explain: "Compressor bleed air warms the inlet lip (and sometimes the cowl), preventing ice at a small performance cost." },
    { q: "Engine inlets are typically 'anti-iced' rather than 'de-iced' because…", options: ["It is cheaper", "Shed ice must be avoided at the compressor face, so ice is prevented continuously", "De-icing is illegal", "The inlet cannot be heated"], answer: 1,
      explain: "Anti-ice runs continuously to prevent any ice forming, since letting ice build and shed is exactly the hazard to avoid." },
  ],
  "2.5": [
    { q: "The compressor map plots pressure ratio against…", options: ["Fuel flow", "Corrected mass flow, with speed and efficiency lines", "Oil temperature", "Altitude only"], answer: 1,
      explain: "The map shows pressure ratio vs corrected mass flow, crossed by constant-speed lines and efficiency contours." },
    { q: "Surge margin is…", options: ["The distance from idle to full power", "The gap between the working line and the surge line", "The fuel reserve", "The oil quantity"], answer: 1,
      explain: "It is the safety buffer between where the compressor operates and where its flow would break down." },
    { q: "Trim balancing of the fan is done to…", options: ["Increase thrust", "Cancel imbalance and control vibration", "Add fuel", "Cool the blades"], answer: 1,
      explain: "Small trim weights cancel the fan's residual imbalance, reducing vibration that would otherwise fatigue structures." },
  ],
  "2.6": [
    { q: "The difference between compressor stall and surge is that…", options: ["They are identical", "Stall is a local blade flow separation; surge is a full-engine flow reversal", "Surge is milder than stall", "Stall only happens on the ground"], answer: 1,
      explain: "Stall is localised (a rotating stall cell); surge is the severe, complete reversal of flow through the whole compressor." },
    { q: "Which can trigger surge?", options: ["Inlet distortion, throttle slams, FOD or fouling", "Adding oil", "Closing the cabin door", "Lowering the landing gear"], answer: 0,
      explain: "Anything that pushes the operating point toward the surge line — distortion, rapid throttle, ingestion, fouling or vane/bleed faults." },
    { q: "A compressor surge is often…", options: ["Silent and harmless", "Audible as a loud bang with thrust loss and high EGT", "A normal cruise event", "Only visible on radar"], answer: 1,
      explain: "The momentary flow reversal produces a bang, thrust loss, high EGT and mechanical/thermal shock." },
  ],
  "2.7": [
    { q: "Bleed valves improve low-speed stability by…", options: ["Adding fuel", "Dumping excess front-stage air the rear stages can't swallow", "Cooling the cabin", "Increasing turbine temperature"], answer: 1,
      explain: "At low speed the front stages pump more than the rear can accept; bleeds dump the excess to prevent front-stage stall." },
    { q: "Variable stator vanes (VSVs) work by…", options: ["Adding more blades", "Rotating to keep blade incidence correct as speed changes", "Spraying water", "Reversing the flow"], answer: 1,
      explain: "By changing the angle at which air meets the next rotor, VSVs keep the compressor efficient and stall-free off-design." },
    { q: "Airflow-control devices are scheduled by the control unit against…", options: ["Cabin altitude", "Corrected engine speed (and sometimes temperature)", "Fuel colour", "Time of day"], answer: 1,
      explain: "Vane angle and bleed opening are scheduled against corrected speed to trim the compressor geometry to the operating point." },
  ],
  "2.8": [
    { q: "In a combustor, only about a quarter of the air enters the…", options: ["Dilution zone", "Primary (combustion) zone", "Turbine", "Bypass duct"], answer: 1,
      explain: "The primary zone gets roughly the right fuel-air ratio to burn; the rest of the air completes the burn and cools the gas." },
    { q: "The dilution zone's job is to…", options: ["Ignite the fuel", "Mix in remaining air to cool the gas to a turbine-safe temperature", "Store fuel", "Reverse thrust"], answer: 1,
      explain: "Dilution air cools the combustion gas to a temperature the turbine can survive and shapes the outlet temperature profile." },
    { q: "Which combustor type dominates modern airliner engines?", options: ["Can (tubular)", "Annular", "Piston", "None — they have no combustor"], answer: 1,
      explain: "Annular combustors are compact, light and give an even outlet temperature, so they dominate modern engines." },
  ],
  "2.9": [
    { q: "Nozzle guide vanes (NGVs) in the turbine…", options: ["Rotate to extract work", "Accelerate and turn the hot gas onto the rotating blades", "Store fuel", "Cool the cabin"], answer: 1,
      explain: "The stationary NGVs speed up and angle the gas so it strikes the turbine rotor blades efficiently." },
    { q: "A fir-tree root is used to…", options: ["Cool the blade", "Lock each blade into the disk against centrifugal load", "Add fuel", "Reduce noise"], answer: 1,
      explain: "The serrated fir-tree root spreads the blade's tonnes of centrifugal force into the disk while allowing thermal expansion." },
    { q: "Turbines need only a few stages to drive many compressor stages because…", options: ["They are bigger", "Falling pressure makes energy extraction aerodynamically easier", "They use more fuel", "They spin slower"], answer: 1,
      explain: "Extracting work with a falling pressure is easier than adding it against a rising pressure, so turbines are more 'work-dense'." },
  ],
  "2.10": [
    { q: "Creep in a turbine blade is…", options: ["Sudden brittle fracture", "Slow permanent stretch under sustained stress at high temperature", "A cooling method", "A type of coating"], answer: 1,
      explain: "Creep is time-dependent permanent elongation under stress and heat; it is a primary life-limiting mechanism for blades." },
    { q: "Blade film cooling works by…", options: ["Spraying water on the blade", "Bleeding cool air through tiny holes to form a protective film", "Slowing the engine", "Removing the blade"], answer: 1,
      explain: "Cool compressor air passes through internal passages and out through holes, shielding the blade so gas can run hotter than the metal." },
    { q: "A single-crystal turbine blade is superior because it…", options: ["Is cheaper", "Removes grain boundaries that weaken the blade in creep", "Needs no cooling", "Is made of plastic"], answer: 1,
      explain: "Casting the blade as one crystal eliminates the grain boundaries where creep damage would otherwise concentrate." },
  ],
  "2.11": [
    { q: "A simple convergent nozzle is suitable for…", options: ["Supersonic jet velocities", "Subsonic engines, accelerating gas up to sonic speed", "Storing fuel", "Reversing thrust"], answer: 1,
      explain: "A convergent nozzle can accelerate the gas only up to the local speed of sound — fine for subsonic engines." },
    { q: "When a nozzle is 'choked'…", options: ["It is blocked by debris", "Flow has reached sonic velocity and exit pressure stays above ambient", "The engine has failed", "Fuel stops flowing"], answer: 1,
      explain: "At sonic throat velocity the convergent nozzle can pass no more velocity, leaving exit pressure above ambient — the pressure-thrust condition." },
    { q: "Variable-area nozzles are needed mainly on…", options: ["Gliders", "Military engines with reheat/afterburning", "APUs", "Piston engines"], answer: 1,
      explain: "Reheat greatly increases exhaust volume, so the nozzle must open and close to stay matched across dry and reheated operation." },
  ],
  "2.12": [
    { q: "Chevrons on a nozzle reduce noise by…", options: ["Adding thrust", "Smoothing the mixing of fast exhaust with still air", "Cooling the turbine", "Storing fuel"], answer: 1,
      explain: "The saw-tooth trailing edge smooths the shear between exhaust and ambient air, cutting the low-frequency mixing noise." },
    { q: "A cascade thrust reverser works by…", options: ["Stopping the engine", "Turning bypass air forward through cascade vanes behind blocker doors", "Adding fuel", "Cooling the cabin"], answer: 1,
      explain: "Blocker doors close the bypass duct and route the cold air through forward-facing cascade vanes to create a retarding force." },
    { q: "Thrust reversers are allowed to deploy only…", options: ["In cruise", "On the ground, under weight-on-wheels and other fail-safe interlocks", "During take-off", "Whenever the pilot wishes"], answer: 1,
      explain: "In-flight deployment is catastrophic, so reversers use strict ground-only interlocks and fail safe (stow) if anything is wrong." },
  ],

  "3.1": [
    { q: "The correct order of the fuel path from tank to combustor is…", options: ["Nozzles → FCU → HP pump → filter → boost pump", "Boost pump → filter → HP pump → FCU → flow divider → nozzles", "HP pump → nozzles → boost pump", "FCU → boost pump → filter"], answer: 1,
      explain: "Fuel is boosted, filtered, pressurised, metered, then divided and sprayed — each stage prepares it for clean combustion." },
    { q: "The fuel/oil heat exchanger performs two jobs:", options: ["Cools fuel and warms oil", "Warms fuel (preventing ice) and cools oil", "Filters fuel and oil", "Pressurises both"], answer: 1,
      explain: "Hot oil warms cold fuel (melting ice crystals, preventing filter icing) while the fuel cools the oil — a neat two-for-one." },
    { q: "Poor fuel atomisation at the nozzles can cause…", options: ["Better efficiency", "Hot streaks that damage the turbine and poor light-up", "Lower EGT", "More thrust"], answer: 1,
      explain: "A poorly-shaped spray burns unevenly, creating hot streaks that damage the turbine and causing carbon build-up and hard starts." },
  ],
  "3.2": [
    { q: "During acceleration, the fuel schedule must stay below which limits?", options: ["The flame-out limit", "The surge and over-temperature limits", "The oil-pressure limit", "The cabin-altitude limit"], answer: 1,
      explain: "Over-fuelling on acceleration would push the compressor to surge and spike turbine temperature, so the schedule caps fuel below both." },
    { q: "During deceleration, the fuel schedule must stay above the…", options: ["Surge limit", "Flame-out (minimum-fuel) limit", "Over-temp limit", "Maximum-thrust limit"], answer: 1,
      explain: "Under-fuelling on deceleration risks blowing the flame out, so a minimum-fuel schedule keeps the flame lit." },
    { q: "Compared with a hydromechanical unit, electronic (FADEC) metering offers…", options: ["Less precision", "Greater precision, adaptability and built-in protection", "No diagnostics", "Mechanical cams only"], answer: 1,
      explain: "FADEC schedules fuel digitally with far greater precision, adaptability, protection and diagnostics than a mechanical HMU." },
  ],
  "3.3": [
    { q: "'Full authority' in FADEC means the controller…", options: ["Only advises the pilot", "Alone commands fuel and engine geometry within certified limits", "Controls the cabin", "Has no sensors"], answer: 1,
      explain: "The EEC alone decides fuel flow, vane angles, bleeds and start sequencing — the pilot just commands thrust with the throttle." },
    { q: "FADEC keeps a single failure from stopping the engine by using…", options: ["A backup pilot", "Dual (A/B) redundant channels", "A bigger fuel tank", "Mechanical cams"], answer: 1,
      explain: "Two independent channels run in parallel; if the active one fails, the standby takes over seamlessly." },
    { q: "A key benefit of FADEC is…", options: ["Higher crew workload", "Built-in protection against over-speed, over-temp and surge", "No diagnostics", "Manual start only"], answer: 1,
      explain: "FADEC optimises performance, protects the engine automatically, auto-starts, and records diagnostics — all reducing crew workload." },
  ],
  "3.4": [
    { q: "The flow divider brings in nozzle circuits progressively to…", options: ["Cool the oil", "Keep the spray pattern correct as fuel pressure rises", "Filter the fuel", "Start the engine"], answer: 1,
      explain: "As demand and pressure rise, the divider stages primary then secondary nozzles so atomisation stays good across the range." },
    { q: "An HP shut-off valve exists mainly to…", options: ["Increase thrust", "Cut fuel to the engine instantly for fire safety", "Warm the fuel", "Meter the fuel"], answer: 1,
      explain: "The high-pressure shut-off (often the fire handle's function) can stop fuel to the engine immediately." },
    { q: "Warming the fuel in the heat exchanger prevents…", options: ["High EGT", "Ice crystals from blocking the fuel filter", "Compressor stall", "Low oil pressure"], answer: 1,
      explain: "At altitude, cold fuel can form ice that blocks filters; warming it with hot oil prevents fuel-system icing." },
  ],
  "3.5": [
    { q: "The starter's job is to…", options: ["Ignite the fuel", "Spin the core to establish airflow before fuel and ignition", "Meter the fuel", "Cool the turbine"], answer: 1,
      explain: "The starter rotates the HP spool so air is flowing through the compressor and combustor before fuel and ignition are added." },
    { q: "A hung start is when the engine…", options: ["Over-temps rapidly", "Lights but stalls at a speed below idle", "Never lights", "Accelerates too fast"], answer: 1,
      explain: "A hung start lights off but lacks the energy to accelerate past a low speed below idle — the start must be aborted." },
    { q: "A hot start is recognised by…", options: ["Low EGT", "EGT rising too fast or too high, threatening the turbine", "No N2 rise", "High oil pressure"], answer: 1,
      explain: "Excessive or rapid EGT rise during start threatens the turbine and requires an immediate abort (fuel off)." },
  ],
  "3.6": [
    { q: "The airline-standard engine starter is usually…", options: ["A hand crank", "A pneumatic air-turbine starter", "A rocket", "A rubber band"], answer: 1,
      explain: "A compact air-turbine motor, spun by APU/ground/cross-bleed air, is light and powerful — the airline norm." },
    { q: "A starter-generator is attractive because it…", options: ["Needs bleed air", "Motors the engine for start, then generates electrical power", "Cannot start the engine", "Only works in flight"], answer: 1,
      explain: "It does double duty — starting the engine and then supplying electrical power once running — with no air supply needed." },
    { q: "Cross-bleed starting uses…", options: ["A ground power cart", "Bleed air from another already-running engine", "The battery only", "Ram air"], answer: 1,
      explain: "When no APU or ground cart is available, air from a running engine can drive the pneumatic starter of another." },
  ],
  "3.7": [
    { q: "Engine ignition uses high-energy capacitor-discharge because it must…", options: ["Save weight only", "Reliably light a cold, poorly-atomised mixture, even at altitude", "Look impressive", "Replace the starter"], answer: 1,
      explain: "Altitude relight demands a spark far stronger than automotive ignition, so capacitor-discharge exciters store and dump intense energy." },
    { q: "Once the flame is self-sustaining, ignition is usually…", options: ["Left on forever", "Switched off to save igniter-plug life", "Made stronger", "Removed"], answer: 1,
      explain: "The flame then propagates continuously without sparks, so ignition is switched off to preserve plug life — unless precautionary." },
    { q: "Ignition is typically selected ON for…", options: ["Cruise only", "Take-off, landing and heavy rain/icing/turbulence", "Parking", "Refuelling"], answer: 1,
      explain: "Ignition is armed when flame-out is more likely and an immediate relight is wanted — take-off, landing and severe weather." },
  ],
  "3.8": [
    { q: "The ignition exciter's role is to…", options: ["Spray fuel", "Step up and store energy, then discharge it to the igniter", "Cool the plug", "Spin the starter"], answer: 1,
      explain: "It steps up low-voltage input, stores charge in a capacitor, then dumps a high-energy pulse to the igniter plug." },
    { q: "Which is a genuine hazard when maintaining ignition systems?", options: ["The exciter holds lethal energy even after power-off", "The plugs are radioactive", "The leads are explosive", "Nothing — it is safe to touch live"], answer: 0,
      explain: "Stored exciter energy persists after power is removed, so lock-out and the specified wait are mandatory before touching ignition." },
    { q: "High-tension leads are shielded to…", options: ["Add weight", "Carry the pulse safely without radiating interference or arcing", "Cool the fuel", "Meter fuel"], answer: 1,
      explain: "Shielding contains the intense pulse, preventing interference and protecting technicians and other systems." },
  ],
  "3.9": [
    { q: "A typical start sequence is…", options: ["Fuel → light-off → starter → ignition", "Starter → N2 rise → ignition → fuel → light-off → idle", "Ignition → idle → starter", "Idle → fuel → starter"], answer: 1,
      explain: "The starter builds airflow, then ignition and fuel are introduced at the scheduled speed, light-off occurs, and the engine spools to idle." },
    { q: "Which set of gauges best confirms a healthy start?", options: ["Cabin altitude and clock", "N2 rise, EGT light-off within limits, N1 following, fuel flow in range", "Only oil quantity", "Only the fuel gauge"], answer: 1,
      explain: "A prompt N2 rise, EGT light-off peaking within limits, N1 following and correct fuel flow together confirm a good start." },
    { q: "On a modern engine, the start is usually sequenced and protected by…", options: ["The pilot's stopwatch", "FADEC, which aborts abnormal starts", "The cabin crew", "Ground staff manually"], answer: 1,
      explain: "FADEC times fuel and ignition, monitors EGT and speeds, and aborts hot, hung or no-starts automatically." },
  ],
  "3.10": [
    { q: "Around a running engine, the two physical hazard zones are…", options: ["Wings and tail", "Intake ingestion and exhaust blast zones", "Cabin and cockpit", "Cargo hold"], answer: 1,
      explain: "The intake can ingest a person and the exhaust blast can throw one; both zones extend well beyond the engine." },
    { q: "Before working on ignition, a technician must…", options: ["Touch it to check", "Switch it off, wait the specified time and follow lock-out", "Increase the voltage", "Start the engine"], answer: 1,
      explain: "Because the exciter holds lethal stored energy, lock-out/tag-out and the discharge wait are mandatory before contact." },
    { q: "Safe fuel handling requires…", options: ["Ignition sources nearby", "Bonding/grounding, spill control, no ignition sources and a fire watch", "No ventilation", "Open flames for light"], answer: 1,
      explain: "Bonding prevents static ignition; spill control, no ignition sources and a fire watch address the vapour and liquid hazard." },
  ],
  "3.11": [
    { q: "A no-start (no light-off) most likely points to a problem with…", options: ["The oil system", "The fuel or ignition system", "The cabin pressurisation", "The landing gear"], answer: 1,
      explain: "If the engine cranks but never lights, fuel delivery or ignition is the usual culprit." },
    { q: "In steady running, which system holds the operating point?", options: ["The starter", "Fuel metering (FCU/FADEC)", "The igniter", "The APU"], answer: 1,
      explain: "Once running, the starter is disengaged and ignition rests; fuel metering maintains the operating point." },
    { q: "Mapping each component to the event it controls helps because it…", options: ["Adds weight", "Builds the mental model troubleshooting relies on", "Replaces the manual", "Is required by law"], answer: 1,
      explain: "Linking starter→acceleration, igniter→light-off and FCU/FADEC→fuel schedule turns parts into a working model for diagnosis." },
  ],
  "3.12": [
    { q: "A slow N2 rise with no EGT during start most likely indicates…", options: ["A hot start", "A cranking/fuel-or-ignition problem (no light-off)", "An over-speed", "Normal operation"], answer: 1,
      explain: "If N2 rises slowly and EGT never moves, the engine isn't lighting — a fuel or ignition (or insufficient crank) issue." },
    { q: "The main advantage of FADEC over a hydromechanical unit is…", options: ["It is heavier", "Digital adaptability, protection and diagnostics", "It needs no sensors", "It cannot protect the engine"], answer: 1,
      explain: "FADEC computes schedules digitally with adaptability, built-in protection and diagnostics the rigid HMU cannot match." },
    { q: "What distinguishes a hung start from a hot start?", options: ["They are the same", "Hung = stalls below idle; hot = EGT too high/fast", "Hung = over-temp; hot = no light", "Both mean over-speed"], answer: 1,
      explain: "A hung start lacks energy to accelerate past a low speed; a hot start over-temperatures — different faults, both aborted." },
  ],

  "4.1": [
    { q: "Why is turbine temperature (EGT/ITT) so closely watched?", options: ["It sets the cabin temperature", "It limits engine life and thrust — the hot section runs near its material limits", "It measures fuel quantity", "It has no importance"], answer: 1,
      explain: "The turbine entry is the hottest, most vulnerable point; its temperature caps engine life and thrust, so it is monitored closely." },
    { q: "EGT is measured in the exhaust (rather than at turbine entry) because…", options: ["It is more accurate there", "A probe cannot survive the turbine-entry gas, so a downstream proxy is used", "The exhaust is hotter", "It is cheaper only"], answer: 1,
      explain: "The true turbine-entry temperature is too hot to probe directly, so EGT/ITT sample downstream as a protected proxy." },
    { q: "A shrinking EGT margin over the engine's life indicates…", options: ["A cooler engine", "Hot-section deterioration", "More thrust available", "A fuel leak"], answer: 1,
      explain: "As the engine wears, EGT for a given thrust creeps up toward the red-line — the shrinking margin flags hot-section deterioration." },
  ],
  "4.2": [
    { q: "Engine pressure ratio (EPR) is the ratio of…", options: ["Fuel to air", "Turbine-discharge (jet-pipe) total pressure to compressor-inlet total pressure", "Oil to fuel pressure", "N1 to N2"], answer: 1,
      explain: "EPR compares the pressure after the turbine to the inlet pressure, closely reflecting the propulsive pressure rise." },
    { q: "On many modern high-bypass engines, thrust is set using…", options: ["Oil pressure", "Fan speed (N1)", "Cabin altitude", "Fuel temperature"], answer: 1,
      explain: "N1 is robust and, since the fan makes most of the thrust, a direct thrust proxy — the reference on many CFM/GE engines." },
    { q: "An advantage of EPR as a thrust reference is that it…", options: ["Needs no probes", "Cancels ambient pressure changes, staying stable across altitude", "Is unaffected by dirty probes", "Ignores the turbine"], answer: 1,
      explain: "Being a ratio of two pressures, EPR cancels ambient changes — though it does depend on clean, accurate probes." },
  ],
  "4.3": [
    { q: "A loss of oil pressure is serious because…", options: ["It wastes fuel", "Bearings fail quickly without lubrication", "It cools the cabin", "It increases thrust"], answer: 1,
      explain: "Oil lubricates and cools the bearings; without pressure they fail fast, making low oil pressure a time-critical emergency." },
    { q: "If EGT rises but fuel flow is unchanged, this most likely points to…", options: ["A real thrust increase", "An instrumentation or specific-component issue rather than a real thrust change", "More fuel being burned", "Normal operation"], answer: 1,
      explain: "A genuine thrust change moves parameters together; one parameter moving alone suggests an instrument or component fault." },
    { q: "Fuel flow, cross-checked against thrust and speed, helps detect…", options: ["Cabin leaks", "Abnormal operation or deterioration", "Radio faults", "Landing-gear problems"], answer: 1,
      explain: "An unexpectedly high fuel flow for a given thrust, or a schedule mismatch, is a clue to a fault or engine deterioration." },
  ],
  "4.4": [
    { q: "EICAS and ECAM are systems that…", options: ["Control the landing gear", "Gather all engine parameters into one coherent, alerting display", "Meter the fuel", "Start the engine"], answer: 1,
      explain: "They replace dozens of separate instruments with one prioritised, colour-coded, alerting picture of the engines." },
    { q: "On the display, an amber band typically means…", options: ["Normal", "Caution", "The engine is off", "Maximum thrust"], answer: 1,
      explain: "Green is normal, amber is caution, red is the limit — the colour bands guide the crew's attention." },
    { q: "Recorded EICAS/ECAM parameters are valuable to maintenance because they…", options: ["Are deleted after each flight", "Provide the trend and fault history for on-condition maintenance", "Control the autopilot", "Set the cabin temperature"], answer: 1,
      explain: "The same data that alerts the crew becomes the trend/fault history that drives ground-based on-condition maintenance." },
  ],
  "4.5": [
    { q: "Spool speeds N1/N2 are displayed as…", options: ["Raw RPM", "A percentage of a design datum", "Degrees Celsius", "Litres per hour"], answer: 1,
      explain: "Percentages (100% = a defined design speed) let very different actual RPMs be read on one intuitive scale." },
    { q: "Overspeed protection exists to prevent…", options: ["Low fuel flow", "Catastrophic, uncontained disk burst", "Cabin depressurisation", "High oil temperature"], answer: 1,
      explain: "Excessive rotor speed can burst a disk; overspeed governors and FADEC limits cut fuel before that can happen." },
    { q: "Which devices sense spool speed?", options: ["Thermocouples", "Tacho-generators and phonic-wheel/reluctance probes", "Pitot tubes", "Fuel-flow meters"], answer: 1,
      explain: "A tacho-generator's output tracks RPM, and phonic-wheel probes count tooth/blade passages to measure speed." },
  ],
  "4.6": [
    { q: "Rising engine vibration is valuable as an indicator because it…", options: ["Always means a fire", "Climbs before an outright failure, giving early warning", "Sets the thrust", "Measures fuel"], answer: 1,
      explain: "Imbalance, bearing wear or a rub raise vibration ahead of failure, so monitoring it gives early warning." },
    { q: "Vibration is sensed by…", options: ["Thermocouples", "Case-mounted accelerometers", "Fuel-flow meters", "Pitot tubes"], answer: 1,
      explain: "Accelerometers on the engine cases, usually near the bearings, feed a vibration monitoring unit." },
    { q: "High fan vibration is often cured by…", options: ["Adding fuel", "Trim balancing", "Increasing thrust", "Cooling the oil"], answer: 1,
      explain: "Small trim weights cancel the fan's imbalance, restoring smooth running — the routine fix for fan vibration." },
  ],
  "4.7": [
    { q: "The primary output gauge for a turboprop or turboshaft is…", options: ["EPR", "Torque", "Bypass ratio", "Cabin altitude"], answer: 1,
      explain: "Shaft engines make power, not jet thrust, so torque (shaft twist under load) is their primary output indication." },
    { q: "Shaft horsepower is given by…", options: ["Torque ÷ RPM", "Torque × RPM (with a constant)", "RPM alone", "Fuel flow × EGT"], answer: 1,
      explain: "Power = torque × rotational speed; at a governed constant prop speed, torque alone reads power." },
    { q: "Torque is limited in operation mainly to…", options: ["Save fuel", "Protect the gearbox and shaft", "Increase EGT", "Cool the cabin"], answer: 1,
      explain: "A torque limit protects the highly-stressed reduction gearbox and shaft; power is set by torque or temperature, whichever limits first." },
  ],
  "4.8": [
    { q: "Power augmentation is needed mainly because thrust falls with…", options: ["Fuel colour", "Altitude and rising ambient temperature", "Cabin pressure", "Oil level"], answer: 1,
      explain: "Thin, hot air reduces mass flow and thrust; augmentation temporarily boosts thrust above the dry rating to compensate." },
    { q: "How do injection and afterburning differ?", options: ["They are identical", "Injection boosts mass flow (density); afterburning adds heat/jet velocity", "Injection adds heat; afterburning cools", "Both remove the turbine"], answer: 1,
      explain: "Injection raises charge density and mass flow; afterburning burns extra fuel downstream to add energy and jet velocity." },
    { q: "Modern civil high-bypass engines generally…", options: ["Use afterburners", "Use neither augmentation — they are sized to make enough dry thrust", "Use water injection on every flight", "Cannot make take-off thrust"], answer: 1,
      explain: "Powerful, efficient high-bypass engines are simply sized for their thrust, avoiding the cost and complexity of augmentation." },
  ],
  "4.9": [
    { q: "Water injection increases thrust by…", options: ["Adding heat", "Raising charge density, so more mass flows through the engine", "Reducing mass flow", "Cooling the cabin"], answer: 1,
      explain: "Water adds mass and its evaporation cools the air, raising density and mass flow — and thrust depends on mass flow." },
    { q: "Water injection is limited to a short burst because…", options: ["It overheats the engine", "The water is a consumable carried in a tank that empties", "It is illegal", "It stops the compressor"], answer: 1,
      explain: "The dedicated water tank lasts only a minute or two — enough for the take-off run — then the boost ends." },
    { q: "Water is typically injected at the…", options: ["Nozzle exit only", "Compressor inlet or the combustor/diffuser", "Oil tank", "Cabin"], answer: 1,
      explain: "Inlet injection cools and densifies the incoming air; combustor injection adds mass and lets more fuel burn within limits." },
  ],
  "4.10": [
    { q: "Adding methanol to injection water provides…", options: ["Only colour", "Antifreeze plus a little combustible energy", "Extra weight only", "A cooling gas"], answer: 1,
      explain: "Methanol lowers the freezing point (antifreeze) and, being combustible, adds a small amount of fuel energy." },
    { q: "The main purpose of water-methanol injection is to…", options: ["Cool the cabin", "Restore take-off thrust lost to high ambient temperature", "Increase cruise range", "Replace the starter"], answer: 1,
      explain: "Like plain water, it boosts mass flow to recover hot-day take-off thrust, with the methanol's energy as a bonus." },
    { q: "Compared with plain water, water-methanol is usable in cold conditions because…", options: ["It is heavier", "The methanol stops the mixture freezing", "It needs no tank", "It burns cooler"], answer: 1,
      explain: "Plain water can freeze at altitude or in cold tanks; methanol as antifreeze keeps the mixture liquid across climates." },
  ],
  "4.11": [
    { q: "Afterburning produces extra thrust by…", options: ["Adding a second compressor", "Burning extra fuel in the jet pipe's spare oxygen", "Cooling the exhaust", "Reducing fuel flow"], answer: 1,
      explain: "The lean core exhaust still has free oxygen; burning fuel in the jet pipe adds heat and jet velocity for a large thrust boost." },
    { q: "A variable-area nozzle is essential with an afterburner because it…", options: ["Looks impressive", "Opens with reheat to pass the extra exhaust volume and avoid surging the core", "Cools the fuel", "Meters the water"], answer: 1,
      explain: "Lighting reheat greatly increases exhaust volume; the nozzle must open in step, or back-pressure could surge the compressor." },
    { q: "The major drawback of afterburning is…", options: ["It reduces thrust", "Enormous fuel consumption", "It cools the engine too much", "It cannot be switched off"], answer: 1,
      explain: "Afterburner fuel flow is huge for its thrust boost, so reheat is used only briefly on military engines." },
  ],
  "4.12": [
    { q: "The best way to judge engine condition from the instruments is to…", options: ["Read one dial only", "Read the whole set as a system, looking for a parameter out of family", "Ignore the gauges", "Only watch fuel flow"], answer: 1,
      explain: "Condition shows in the whole picture — thrust set, EGT margin, vibration, and whether any parameter is out of family." },
    { q: "For a large, brief military thrust boost, the right augmentation is…", options: ["Water injection", "Afterburning", "Compressor washing", "Trim balancing"], answer: 1,
      explain: "Afterburning gives the big, short boost military aircraft need; injection is a hot-day take-off restorer." },
    { q: "One parameter moving alone (others steady) usually means…", options: ["A real thrust change", "An instrument fault or specific-component problem", "A fuel leak in every system", "Normal thrust setting"], answer: 1,
      explain: "A genuine thrust change is consistent across parameters; a lone mover points to instrumentation or one component." },
  ],

  "5.1": [
    { q: "On-condition maintenance means an engine is maintained…", options: ["Only on fixed intervals", "On the evidence of its condition, as long as it stays healthy", "Never", "Only after failure"], answer: 1,
      explain: "It keeps the engine in service while the evidence says it is healthy, acting when the evidence says otherwise — maximising life and availability safely." },
    { q: "Which is NOT a normal engine-health data source?", options: ["Recorded flight parameters", "Oil analysis", "Vibration monitoring", "Cabin lighting status"], answer: 3,
      explain: "Health monitoring draws on flight parameters, oil analysis, vibration and borescope — not cabin lighting." },
    { q: "The real power of health monitoring comes from…", options: ["Reading one indicator", "Correlating the several data streams together", "Ignoring trends", "Waiting for failure"], answer: 1,
      explain: "No single indicator is conclusive; correlating trend, oil, vibration and borescope gives the true health picture." },
  ],
  "5.2": [
    { q: "A key purpose of a ground run is to…", options: ["Refuel the aircraft", "Verify performance and confirm maintenance was done correctly", "Clean the cabin", "Charge the battery only"], answer: 1,
      explain: "Ground runs prove performance, confirm repairs (leak/idle/accel checks) and survey vibration before the engine flies." },
    { q: "An instrumented test cell is used to…", options: ["Store the engine", "Measure actual thrust and full performance under controlled conditions", "Paint the engine", "Refuel"], answer: 1,
      explain: "The test cell measures real thrust, fuel flow, temperatures and speeds, corrected to standard conditions, against the acceptance spec." },
    { q: "Rushing the warm-up or cool-down of a ground run risks…", options: ["Nothing", "Thermally shocking the engine", "Saving the engine", "Higher thrust"], answer: 1,
      explain: "The warm-up/stabilise/cool-down procedure exists to avoid thermal shock — the discipline protects the hardware." },
  ],
  "5.3": [
    { q: "The correct structure for troubleshooting is…", options: ["Swap parts until it works", "Symptom → possible causes → tests → confirmed fault", "Guess the cause", "Ignore the symptom"], answer: 1,
      explain: "Structured diagnosis reasons from the symptom through possible causes and discriminating tests to the confirmed fault." },
    { q: "Vibration at a bearing-defect frequency most likely indicates…", options: ["Fan imbalance", "A bearing problem", "A fuel leak", "Normal running"], answer: 1,
      explain: "Frequency content localises the source; a bearing-defect frequency points to a bearing rather than fan imbalance." },
    { q: "Why is maintenance and flight history part of the evidence?", options: ["It isn't relevant", "It gives context — e.g. a vibration right after a blade change vs a months-long trend", "It replaces the gauges", "It sets the thrust"], answer: 1,
      explain: "Recent maintenance, flight profile and the leading trend change what a symptom means — history is diagnostic evidence." },
  ],
  "5.4": [
    { q: "The two lethal physical hazard zones around a running engine are…", options: ["Cockpit and cabin", "Intake ingestion and exhaust blast", "Wings and tail", "Nose and gear"], answer: 1,
      explain: "The intake can ingest a person and the exhaust blast can hurl objects and people; both grow with power." },
    { q: "Near a running engine, hearing protection is…", options: ["Optional", "Required at all times", "Only for pilots", "Never needed"], answer: 1,
      explain: "Engine noise is extreme; hearing protection is mandatory whenever near a running engine." },
    { q: "FOD discipline protects…", options: ["Only the paperwork", "Both the engine (from ingestion) and people (from ingested-object/blast injury)", "Only the cabin", "Nothing"], answer: 1,
      explain: "Keeping the area clear of debris protects the engine from ingestion and people from injury — a shared safety culture." },
  ],
  "5.5": [
    { q: "Trend monitoring is valuable because a single reading…", options: ["Is always wrong", "Can look normal while the trend reveals slow degradation", "Replaces the trend", "Sets the thrust"], answer: 1,
      explain: "One reading may look fine; plotting the corrected parameter over many flights reveals whether the engine is drifting." },
    { q: "The headline trend for hot-section health is…", options: ["Cabin altitude", "EGT margin", "Fuel colour", "Tyre pressure"], answer: 1,
      explain: "A shrinking EGT margin — the gap to the red-line at a reference thrust — signals hot-section deterioration or fouling." },
    { q: "An EGT-margin drop that recovers after a compressor wash was caused by…", options: ["Hot-section wear", "Fouling", "A fuel leak", "Overspeed"], answer: 1,
      explain: "If a wash restores the margin, the loss was recoverable fouling; a margin that doesn't recover indicates real hot-section wear." },
  ],
  "5.6": [
    { q: "A magnetic chip detector captures…", options: ["Fuel vapour", "Ferrous wear debris from the oil", "Air bubbles", "Water"], answer: 1,
      explain: "Magnetic plugs in the oil system capture ferrous debris shed by wearing bearings and gears for inspection." },
    { q: "Spectrometric oil analysis (SOAP) localises wear by…", options: ["Measuring oil colour", "Identifying which wear-metal alloy is rising", "Weighing the oil", "Counting flights"], answer: 1,
      explain: "Different components use different alloys, so the rising metal points to the specific part that is wearing." },
    { q: "Oil analysis is uniquely valuable because it…", options: ["Sets the thrust", "Reveals hidden internal wear no external gauge can see", "Cools the engine", "Meters the fuel"], answer: 1,
      explain: "Bearings and gears are hidden, but their wear metals reach the oil — a window into internal mechanical health." },
  ],
  "5.7": [
    { q: "In service, vibration is analysed for frequency content in order to…", options: ["Increase thrust", "Localise the source — fan, a spool, or a bearing", "Cool the oil", "Meter fuel"], answer: 1,
      explain: "Tracked-order and defect frequencies distinguish fan imbalance from HP-spool or bearing problems." },
    { q: "Vibration at the fan/LP rotational frequency usually indicates…", options: ["A bearing failure", "Fan imbalance", "A fuel leak", "Overspeed"], answer: 1,
      explain: "Synchronous vibration at the fan's frequency points to imbalance — a moved/damaged blade, ice or fouling." },
    { q: "Bearing-frequency vibration with oil-debris findings points to…", options: ["Trim balancing on-wing", "Internal wear that may require removal", "A cabin fault", "Normal running"], answer: 1,
      explain: "That combination is not a balancing issue but internal wear — distinguishing it is exactly what frequency analysis enables." },
  ],
  "5.8": [
    { q: "A borescope allows a technician to…", options: ["Remove the engine faster", "Inspect the engine interior through ports without a teardown", "Refuel the engine", "Balance the fan"], answer: 1,
      explain: "The optical probe reveals internal cracks, burning, erosion and FOD through access ports — no costly disassembly." },
    { q: "To inspect each turbine blade with a borescope, the technician uses a…", options: ["Fuel pump", "Rotor-turning tool to rotate the rotor", "Fire extinguisher", "Torque wrench only"], answer: 1,
      explain: "A manual or motorised turning tool rotates the rotor so blades can be inspected one by one, stage by stage." },
    { q: "A borescope finding beyond the manual's allowable limits drives…", options: ["Nothing", "Repair or removal", "A wash only", "More thrust"], answer: 1,
      explain: "Within-limit defects are monitored; beyond-limit defects are measured, logged and drive repair or removal." },
  ],
  "5.9": [
    { q: "Allowable damage and wear limits in the manuals exist to…", options: ["Make inspection subjective", "Turn 'looks worn' into an objective, repeatable judgement", "Slow work down", "Replace documentation"], answer: 1,
      explain: "Defined limits let any inspector reach the same, consistent disposition for a given defect." },
    { q: "The three inspection dispositions are…", options: ["Fast, slow, medium", "Serviceable, repairable, reject", "Hot, cold, warm", "New, old, spare"], answer: 1,
      explain: "Each finding is judged serviceable (return to service), repairable (restorable) or reject (replace)." },
    { q: "Documenting inspections and dispositions is…", options: ["Optional paperwork", "Required for airworthiness and future trend comparison", "Only for training", "Unnecessary"], answer: 1,
      explain: "The record proves airworthiness, supports trend comparison and is a legal/regulatory requirement." },
  ],
  "5.10": [
    { q: "Compressor fouling reduces performance by…", options: ["Cooling the blades", "Roughening blades, cutting efficiency and mass flow (raising EGT/fuel)", "Adding thrust", "Cleaning the engine"], answer: 1,
      explain: "Salt/dust deposits roughen the blades, lowering compressor efficiency and eating into the EGT margin." },
    { q: "An off-line (crank) wash differs from an on-line wash in that it…", options: ["Runs at full power", "Motors the engine without firing for a more thorough clean", "Uses no water", "Is done in flight"], answer: 1,
      explain: "Crank washing motors the unfired engine for a deeper clean and bigger recovery than routine on-line washing." },
    { q: "A benefit of compressor washing is…", options: ["Higher EGT", "Lower fuel flow and EGT, restoring margin", "More fouling", "Less thrust"], answer: 1,
      explain: "Cleaning recovers efficiency, lowering fuel burn and EGT for the same thrust and restoring the EGT margin." },
  ],
  "5.11": [
    { q: "Which is a common source of FOD?", options: ["Clean cabin air", "Ramp debris, birds/ice and tools left behind in maintenance", "Engine oil", "Radio waves"], answer: 1,
      explain: "FOD comes from ramp debris, nature (birds/ice) and maintenance items — anything the engine can ingest." },
    { q: "A small nick from FOD matters because it…", options: ["Improves the blade", "Raises stress and can start a fatigue crack", "Cools the blade", "Adds thrust"], answer: 1,
      explain: "Nicks concentrate stress and can initiate fatigue cracks, so they must be blended or monitored against limits." },
    { q: "FOD prevention relies mainly on…", options: ["A single device", "Discipline — FOD walks, inlet covers, tool control and design measures", "Ignoring the ramp", "More fuel"], answer: 1,
      explain: "Because FOD is caused by lapses, prevention is a culture of cleanliness and tool control, not one gadget." },
  ],
  "5.12": [
    { q: "The capstone skill of engine monitoring is to…", options: ["Read one gauge", "Integrate trend, oil, vibration and borescope evidence into a decision", "Ignore the data", "Only wash the engine"], answer: 1,
      explain: "Real decisions correlate the streams — e.g. wash-recoverable EGT vs borescope-confirmed wear, or bearing vibration with SOAP metal." },
    { q: "An EGT-margin loss that does NOT recover after a wash, with borescope findings, indicates…", options: ["Fouling", "Hot-section wear", "A fuel leak", "Normal wear-in"], answer: 1,
      explain: "Non-recoverable margin plus corroborating borescope evidence points to genuine hot-section deterioration, not fouling." },
    { q: "From the combined evidence, the maintainer chooses among…", options: ["Only removal", "Wash, borescope/inspect, repair or remove — matched to the evidence", "Only washing", "Nothing"], answer: 1,
      explain: "The action follows the evidence: wash recoverable fouling, inspect to confirm, repair a restorable finding, or remove a failure." },
  ],
};
