// GTEM Learning Bay — curriculum data (single source of truth).
// 5 units × 12 sessions = 60. Transcribed from the lesson plan
// "Gas Turbine Engine Module" (24CBAV53 · B.Sc Aviation · Sem V · 4 credits · 60h).
// Each session: { id, n, title, method, summary, points[], visual (component key
//   in app/gtem/visuals) }. Content/quiz/videos live in the sibling data files.

export const COURSE = {
  code: "24CBAV53",
  title: "Gas Turbine Engine Module",
  program: "B.Sc Aviation · Semester V",
  instructor: "Thokala Rohit",
  hours: 60,
  books: [
    "Rolls-Royce — The Jet Engine (6th ed.)",
    "EASA Part-66 Module 15 — Gas Turbine Engine",
    "Irwin E. Treager — Aircraft Gas Turbine Engine Technology (McGraw-Hill)",
    "Hünecke — Jet Engines: Fundamentals of Theory, Design and Operation",
    "Cohen, Rogers & Saravanamuttoo — Gas Turbine Theory",
  ],
};

const P = (t, d) => ({ t, d });

export const UNITS = [
  /* ═══════════════════════ UNIT I ═══════════════════════ */
  {
    id: 1, code: "I", title: "Fundamentals & Performance", accent: "#ff7a1a", accent2: "#ffb454",
    tag: "How it works", icon: "◉",
    blurb: "From energy and Newton's laws to the Brayton cycle, engine types, thrust, and the performance parameters that define a gas turbine.",
    objectives: [
      "Explain the physical and thermodynamic principles of gas turbine propulsion",
      "Describe the construction and operation of turbojet, turbofan, turboprop and turboshaft engines",
      "Calculate thrust and the key engine performance parameters",
      "Evaluate engine efficiencies and design parameters",
      "Interpret gas-flow behaviour, engine ratings and performance limitations",
    ],
    sessions: [
      { id: "1.1", n: 1, title: "Fundamentals of Aircraft Propulsion", method: "Foundations", visual: "PropulsionBasics",
        summary: "Potential and kinetic energy, Newton's laws and the force–work–power chain — the physics that makes a jet engine push an aircraft forward.",
        points: [P("Energy concepts", "Potential and kinetic energy and their conversion drive every propulsion device."), P("Newton's laws of motion", "Thrust is Newton's third law — accelerate a mass of air rearward and the reaction pushes the aircraft forward."), P("Force, work, power & energy", "The relationships between force, work, power, energy, velocity and acceleration underpin engine performance.")] },
      { id: "1.2", n: 2, title: "Thermodynamic Principles", method: "Thermodynamics", visual: "StationPTV",
        summary: "How pressure, temperature and velocity of the air change as it flows through the engine — the thermodynamic story of the gas path.",
        points: [P("Thermodynamic properties of air", "Air is the working fluid; its pressure, temperature and density govern the whole cycle."), P("Airflow through the engine", "Mass flow is continuous — what the compressor takes, the turbine and nozzle must pass."), P("Pressure & temperature variation", "Each component raises or lowers P and T in a predictable, teachable pattern.")] },
      { id: "1.3", n: 3, title: "The Brayton Cycle", method: "The cycle", visual: "BraytonCycle",
        summary: "Compression → combustion → expansion, plotted on P–V and T–S diagrams — the ideal cycle that all gas turbines approximate.",
        points: [P("Introduction to the Brayton cycle", "Constant-pressure heat addition is the defining feature of the gas turbine cycle."), P("Compression & combustion", "The compressor raises pressure; the combustor adds heat energy at (near) constant pressure."), P("Turbine work balance", "The turbine extracts just enough energy to drive the compressor; the rest becomes thrust.")] },
      { id: "1.4", n: 4, title: "Turbojet & Turbofan Engines", method: "Engine types", visual: "EngineExplorer",
        summary: "The two workhorses of jet propulsion — the pure turbojet and the bypass turbofan — their layout and operation.",
        points: [P("Turbojet arrangement & operation", "Intake, compressor, combustor, turbine, nozzle — all core flow becomes the jet."), P("Turbofan arrangement & operation", "A fan moves a large bypass stream for quieter, more efficient thrust."), P("Core vs bypass flow", "High-bypass fans generate most thrust from cold air moving slowly and in bulk.")] },
      { id: "1.5", n: 5, title: "Turboprop & Turboshaft Engines", method: "Engine types", visual: "EngineExplorer",
        summary: "When the turbine's job is to turn a shaft — driving a propeller (turboprop) or a rotor/load (turboshaft).",
        points: [P("Turboprop arrangement & operation", "A power turbine and reduction gearbox drive a propeller; most energy becomes shaft power."), P("Turboshaft arrangement & operation", "A free power turbine drives helicopters, pumps or generators — thrust is negligible."), P("Free vs fixed turbine", "A free turbine decouples the load from the gas generator for flexible operation.")] },
      { id: "1.6", n: 6, title: "Comparison of Engine Types", method: "Comparison", visual: "EngineCompare",
        summary: "Turbojet, turbofan, turboprop, turboshaft — matched to speed, altitude and mission by their thrust and efficiency character.",
        points: [P("Speed & altitude suitability", "Turboprops suit low/slow; turbofans dominate subsonic cruise; turbojets suit high speed."), P("Thrust vs efficiency", "Bypass trades peak jet speed for propulsive efficiency and fuel economy."), P("Selecting an engine", "Mission, noise, fuel and cost decide which architecture an aircraft carries.")] },
      { id: "1.7", n: 7, title: "Engine Thrust Fundamentals", method: "Thrust", visual: "ThrustBuilder",
        summary: "Gross thrust, momentum drag and net thrust — building the thrust equation from the mass and velocity of the gas stream.",
        points: [P("Gross & net thrust", "Gross thrust is the nozzle's total push; net thrust subtracts the momentum drag of incoming air."), P("Choked nozzle thrust", "When the nozzle chokes, pressure thrust adds to momentum thrust."), P("Thrust distribution & resultant", "Thrust is the resultant of forces on every internal surface of the engine.")] },
      { id: "1.8", n: 8, title: "Engine Performance Parameters", method: "Performance", visual: "PerformanceCalc",
        summary: "Thrust horsepower, equivalent shaft horsepower and specific fuel consumption — the numbers that rate an engine's usefulness.",
        points: [P("Thrust & equivalent shaft horsepower", "THP relates thrust to speed; ESHP combines shaft and residual-jet power for props."), P("Specific fuel consumption", "SFC — fuel burned per unit thrust/power — is the headline economy metric."), P("Why these parameters matter", "They let engineers compare very different engines on a common footing.")] },
      { id: "1.9", n: 9, title: "Engine Efficiencies", method: "Efficiency", visual: "EfficiencyDial",
        summary: "Thermal, propulsive and overall efficiency — where the fuel's energy goes and how much becomes useful propulsion.",
        points: [P("Thermal efficiency", "How well the core converts fuel heat into mechanical/kinetic energy."), P("Propulsive efficiency", "How well the jet's kinetic energy is turned into useful thrust power."), P("Overall efficiency", "The product of thermal and propulsive efficiency — the true fuel-to-thrust figure.")] },
      { id: "1.10", n: 10, title: "Engine Design Parameters", method: "Design", visual: "BypassRatio",
        summary: "By-pass ratio and engine pressure ratio — the two design levers that shape a modern engine's economy and noise.",
        points: [P("By-pass ratio", "The mass of bypass air to core air; high BPR means quiet, efficient, big-fan engines."), P("Engine pressure ratio", "EPR (outlet/inlet total pressure) is a key thrust-setting and design parameter."), P("Effect on economy & noise", "Higher BPR improves SFC and cuts jet noise at cruise.")] },
      { id: "1.11", n: 11, title: "Gas Flow Characteristics", method: "Gas path", visual: "StationPTV",
        summary: "Tracking pressure, temperature and velocity station by station — reading the gas-flow behaviour through the whole engine.",
        points: [P("Pressure changes", "Pressure rises through the compressor, is roughly held in combustion, then falls across turbine and nozzle."), P("Temperature changes", "Temperature peaks after combustion and is limited by turbine material capability."), P("Velocity changes", "Velocity is managed by ducts and nozzles to convert between pressure and speed.")] },
      { id: "1.12", n: 12, title: "Engine Ratings & Limitations", method: "Ratings", visual: "EngineRatings",
        summary: "Static thrust, the influence of speed, altitude and hot climate, flat rating and the limits that protect the engine.",
        points: [P("Engine ratings & static thrust", "Take-off, climb and cruise ratings define allowable thrust for time and condition."), P("Speed, altitude & hot climate", "Thrust falls with altitude and rising ambient temperature."), P("Flat rating & limitations", "Flat rating holds thrust up to a corner temperature to protect the hot section.")] },
    ],
  },

  /* ═══════════════════════ UNIT II ═══════════════════════ */
  {
    id: 2, code: "II", title: "Engine Construction", accent: "#22d3ee", accent2: "#67e8f9",
    tag: "Inside the engine", icon: "⚙",
    blurb: "Module by module — inlet, compressors, combustion, turbine and exhaust — how each part is built and why it is shaped the way it is.",
    objectives: [
      "Describe inlet duct design and ice protection",
      "Compare axial and centrifugal compressors and their airflow control",
      "Explain the construction and operation of the combustion and turbine sections",
      "Analyse turbine blade stress, creep and cooling",
      "Describe exhaust systems, nozzles, noise reduction and thrust reversers",
    ],
    sessions: [
      { id: "2.1", n: 1, title: "Engine Inlet & Air Intake Ducts", method: "Inlet", visual: "InletDuct",
        summary: "The inlet's job — deliver clean, smooth, subsonic air to the compressor face across the whole flight envelope.",
        points: [P("Purpose of the inlet", "Recover pressure and slow the air to a speed the compressor can accept."), P("Compressor inlet ducts", "Duct shape controls distortion and pressure recovery."), P("Subsonic vs supersonic inlets", "Supersonic inlets add geometry to manage shock waves.")] },
      { id: "2.2", n: 2, title: "Inlet Configurations & Effects", method: "Inlet", visual: "InletConfig",
        summary: "Pitot, divided, variable-geometry and S-duct inlets — how configuration affects distortion, drag and engine matching.",
        points: [P("Inlet configurations", "Podded, buried, side-mounted and chin inlets suit different airframes."), P("Effect on performance", "Distortion at the compressor face degrades surge margin and thrust."), P("Design trade-offs", "Pressure recovery is balanced against weight, drag and signature.")] },
      { id: "2.3", n: 3, title: "Axial & Centrifugal Compressors", method: "Compressor", visual: "CompressorTypes",
        summary: "Two ways to raise pressure — the multi-stage axial and the single/double-stage centrifugal — and where each is used.",
        points: [P("Axial compressor", "Rows of rotor and stator blades give high mass flow and pressure ratio in a slim engine."), P("Centrifugal compressor", "An impeller flings air outward for a high per-stage pressure rise in a compact package."), P("Applications", "Axials dominate large engines; centrifugals suit small turboprops/APUs.")] },
      { id: "2.4", n: 4, title: "Ice Protection Systems", method: "Protection", visual: "IceProtection",
        summary: "Keeping the inlet and nose cone ice-free — hot-air and electrical anti-ice that protect the compressor from ice shedding.",
        points: [P("Why ice protection", "Ice on the inlet distorts flow and can be ingested, damaging blades."), P("Hot-air anti-ice", "Compressor bleed air warms the inlet lip and nose cowl."), P("Electrical anti-ice", "Heating elements protect probes and, on some engines, the spinner.")] },
      { id: "2.5", n: 5, title: "Compressor Performance & Fan Balancing", method: "Compressor", visual: "FanBalance",
        summary: "Compressor maps, working line and fan balancing — how performance is characterised and how a fan is kept smooth.",
        points: [P("Compressor performance", "The compressor map plots pressure ratio against mass flow and speed lines."), P("Working line & surge margin", "The operating line must stay clear of the surge line."), P("Fan balancing", "Trim balancing minimises vibration from the large rotating fan.")] },
      { id: "2.6", n: 6, title: "Compressor Stall & Surge", method: "Compressor", visual: "StallSurge",
        summary: "When the airflow breaks down — the causes, the difference between stall and surge, and the effects on the engine.",
        points: [P("Compressor stall", "Local blade flow separates when the angle of attack is too high."), P("Compressor surge", "A full-engine flow reversal — violent, audible and potentially damaging."), P("Causes & effects", "Distortion, damage, contamination or mishandling can trigger stall/surge.")] },
      { id: "2.7", n: 7, title: "Airflow Control Systems", method: "Compressor", visual: "AirflowControl",
        summary: "Bleed valves, variable inlet guide vanes and variable stator vanes — the tools that keep the compressor stable off-design.",
        points: [P("Bleed valves", "Dump excess air at low speed to prevent the front stages stalling."), P("Variable IGVs & stator vanes", "Rotate vanes to keep blade incidence correct across the speed range."), P("Why airflow control", "It widens the stable operating range and improves surge margin.")] },
      { id: "2.8", n: 8, title: "Combustion Section", method: "Combustor", visual: "Combustor",
        summary: "Where fuel meets air and burns — primary, secondary and dilution zones that release heat and protect the liner.",
        points: [P("Construction", "Can, annular and can-annular combustors house the flame."), P("Primary/secondary/dilution zones", "Air is staged to burn efficiently and cool the gas before the turbine."), P("Principles of operation", "Stable combustion must be maintained across all conditions.")] },
      { id: "2.9", n: 9, title: "Turbine Section", method: "Turbine", visual: "TurbineStage",
        summary: "Extracting energy from the hot gas — nozzle guide vanes and turbine blades convert heat and pressure into shaft work.",
        points: [P("Operation & characteristics", "Nozzle guide vanes accelerate and turn the gas onto the rotating blades."), P("Turbine blade types", "Impulse, reaction and impulse-reaction blading extract energy differently."), P("Blade-to-disk attachment", "Fir-tree roots hold blades against enormous centrifugal load.")] },
      { id: "2.10", n: 10, title: "Turbine Blade Stress & Creep", method: "Turbine", visual: "CreepStress",
        summary: "The hottest, most stressed parts in the engine — how centrifugal stress and high temperature cause creep, and how cooling fights it.",
        points: [P("Stress on turbine blades", "Centrifugal load and gas bending stress act at extreme temperature."), P("Creep", "Slow permanent stretch under sustained stress and heat limits blade life."), P("Blade cooling", "Internal passages and film cooling let blades run above metal-melting gas temperatures.")] },
      { id: "2.11", n: 11, title: "Exhaust Systems & Nozzles", method: "Exhaust", visual: "Nozzle",
        summary: "Turning residual pressure into jet velocity — convergent, divergent and variable-area nozzles and how choking works.",
        points: [P("Exhaust construction", "The exhaust cone and duct straighten and accelerate the gas."), P("Nozzle types", "Convergent nozzles for subsonic, con-di for supersonic jets."), P("Variable-area nozzles", "Fighters vary nozzle area to match reheat and flight condition.")] },
      { id: "2.12", n: 12, title: "Noise Reduction & Thrust Reversers", method: "Exhaust", visual: "ThrustReverser",
        summary: "Making engines quieter and stopping the aircraft — chevrons and mixers for noise, cascade and clamshell reversers for braking.",
        points: [P("Engine noise reduction", "Chevrons, acoustic liners and high bypass cut jet and fan noise."), P("Thrust reversers", "Cascade, clamshell and blocker-door reversers redirect thrust forward."), P("Operation & safety", "Reversers deploy only on the ground with strict interlocks.")] },
    ],
  },

  /* ═══════════════════════ UNIT III ═══════════════════════ */
  {
    id: 3, code: "III", title: "Fuel, Ignition & Starting", accent: "#f59e0b", accent2: "#fbbf24",
    tag: "Control & light-up", icon: "⛽",
    blurb: "How fuel is metered and controlled (including FADEC), and how the engine is started and lit — safely and repeatably.",
    objectives: [
      "Explain engine fuel systems and fuel metering",
      "Describe electronic engine control (FADEC) and its components",
      "Describe engine starting systems and their types",
      "Explain ignition systems and components",
      "State the maintenance-safety requirements for fuel, ignition and starting",
    ],
    sessions: [
      { id: "3.1", n: 1, title: "Engine Fuel Systems Overview", method: "Fuel", visual: "FuelSystem",
        summary: "From tank to burner — pumps, filters, the fuel control unit and spray nozzles that deliver the right fuel at the right time.",
        points: [P("Purpose of the fuel system", "Supply clean, metered fuel matched to thrust demand and engine condition."), P("Main components", "Boost/HP pumps, filters, FCU/metering unit, flow divider and nozzles."), P("Fuel scheduling", "Fuel must be scheduled for start, accel, steady state and decel without surge or flame-out.")] },
      { id: "3.2", n: 2, title: "Fuel Metering & Control", method: "Fuel", visual: "FuelMetering",
        summary: "The fuel control's balancing act — giving the engine enough fuel to accelerate but never enough to stall, surge or overtemp.",
        points: [P("Metering principle", "Fuel flow is scheduled against RPM, pressures, temperature and throttle."), P("Acceleration & deceleration limits", "Schedules avoid over-fuelling (surge/overtemp) and under-fuelling (flame-out)."), P("Hydromechanical vs electronic", "Older HMUs are giving way to electronic control.")] },
      { id: "3.3", n: 3, title: "FADEC — Electronic Engine Control", method: "FADEC", visual: "FadecLoop",
        summary: "Full Authority Digital Engine Control — sensors feed an EEC that schedules fuel and geometry precisely and protects the engine.",
        points: [P("What FADEC does", "A digital computer has full authority over fuel and engine geometry."), P("Sensors & actuators", "It reads N1/N2, EGT, pressures and commands fuel and vanes."), P("Benefits", "Optimised performance, protection, reduced crew workload and built-in diagnostics.")] },
      { id: "3.4", n: 4, title: "Fuel System Layout & Components", method: "Fuel", visual: "FuelSystem",
        summary: "How the components connect — the full plumbing of a modern engine's fuel system and where each part sits.",
        points: [P("System layout", "Low-pressure and high-pressure circuits with heat exchange and filtration."), P("Fuel/oil heat exchanger", "Warms fuel and cools oil, preventing ice in the fuel."), P("Nozzles & flow divider", "Deliver an atomised, correctly-patterned spray to the combustor.")] },
      { id: "3.5", n: 5, title: "Engine Starting Systems", method: "Starting", visual: "StartSequence",
        summary: "Getting the core spinning — the starter accelerates the compressor to a speed where combustion becomes self-sustaining.",
        points: [P("Purpose of the starter", "Rotate the HP spool to establish airflow before fuel and ignition."), P("Start envelope", "Fuel-on, light-off, self-sustaining and idle speeds define the start."), P("Hung & hot starts", "Recognising abnormal starts protects the engine.")] },
      { id: "3.6", n: 6, title: "Types of Starting Systems", method: "Starting", visual: "StarterTypes",
        summary: "Pneumatic, electric and APU/cross-bleed starting — the common ways to turn a gas turbine over.",
        points: [P("Pneumatic (air) starter", "An air turbine motor spun by APU/ground/cross-bleed air is the airline norm."), P("Electric starter/generator", "Common on small engines and increasingly on large ones."), P("APU & cross-bleed", "Sources of the air that drives pneumatic starters.")] },
      { id: "3.7", n: 7, title: "Ignition Systems", method: "Ignition", visual: "Ignition",
        summary: "The spark that lights the fire — high-energy capacitor-discharge ignition fires the igniter plugs during start and relight.",
        points: [P("Ignition principle", "A high-voltage spark ignites the atomised fuel-air mixture."), P("High-energy ignition", "Capacitor-discharge units store and release intense sparks."), P("When ignition is on", "Start, relight, take-off, and icing/turbulence as selected.")] },
      { id: "3.8", n: 8, title: "Ignition System Components", method: "Ignition", visual: "Ignition",
        summary: "Exciter, leads and igniter plugs — the parts of the ignition circuit and their maintenance considerations.",
        points: [P("Ignition exciter", "Steps up and stores energy for the spark."), P("Igniter plugs", "Surface- or air-gap plugs create the spark in the combustor."), P("High-tension leads", "Shielded leads carry the high-energy pulse safely.")] },
      { id: "3.9", n: 9, title: "Start & Ignition Sequence", method: "Sequence", visual: "StartSequence",
        summary: "The choreographed sequence — starter, ignition and fuel timed together to a stable idle, watched on the gauges.",
        points: [P("Sequence of events", "Starter on → N2 rise → ignition on → fuel on → light-off → idle."), P("Monitoring the start", "EGT, N1, N2 and fuel flow confirm a healthy start."), P("Automatic start control", "FADEC sequences and protects modern starts.")] },
      { id: "3.10", n: 10, title: "Maintenance Safety Requirements", method: "Safety", visual: "SafetyZones",
        summary: "Working safely around fuel, ignition and starting — intake/exhaust hazard zones, high-energy ignition and fuel handling.",
        points: [P("Intake & exhaust danger zones", "Ingestion and blast hazards demand strict ground clearances."), P("High-energy ignition safety", "Lethal voltages require lock-out before touching ignition."), P("Fuel handling & fire safety", "Bonding, spill control and fire watch are mandatory.")] },
      { id: "3.11", n: 11, title: "Fuel, Ignition & Starting Review", method: "Review", visual: "SystemReview",
        summary: "Bringing the unit together — how fuel, ignition and starting interact through a normal engine start and run.",
        points: [P("System integration", "Starting, ignition and fuel systems act in concert."), P("Common faults", "No-start, hot start, hung start and their likely causes."), P("Consolidation", "Linking components to the events they control.")] },
      { id: "3.12", n: 12, title: "Unit Assessment & Discussion", method: "Assessment", visual: "SystemReview",
        summary: "Consolidating Unit III with worked problems, troubleshooting scenarios and a knowledge check.",
        points: [P("Scenario analysis", "Diagnose start and fuel faults from symptoms."), P("Discussion", "Compare hydromechanical and FADEC control."), P("Self-assessment", "Confirm mastery of fuel, ignition and starting.")] },
    ],
  },

  /* ═══════════════════════ UNIT IV ═══════════════════════ */
  {
    id: 4, code: "IV", title: "Indication & Power Augmentation", accent: "#ff5722", accent2: "#ff8a65",
    tag: "Instruments & more thrust", icon: "❰❱",
    blurb: "Reading the engine through its instruments — temperature, pressure, speed, vibration and torque — and squeezing out extra thrust.",
    objectives: [
      "Describe EGT/ITT and engine thrust indication systems",
      "Explain oil-pressure, speed, vibration and torque indication",
      "Interpret engine instruments for condition and thrust setting",
      "Describe power-augmentation systems",
      "Explain water/water-methanol injection and afterburning",
    ],
    sessions: [
      { id: "4.1", n: 1, title: "EGT / Interstage Turbine Temperature", method: "Temperature", visual: "EgtGauge",
        summary: "Watching the hot section — exhaust-gas and interstage turbine temperature protect the most heat-limited parts of the engine.",
        points: [P("Why temperature is measured", "Turbine temperature limits engine life and thrust."), P("EGT & ITT", "Thermocouples sample gas temperature at or before the turbine."), P("Reading the gauge", "Exceedances are time-limited and logged for the hot section.")] },
      { id: "4.2", n: 2, title: "Engine Thrust Indication", method: "Thrust set", visual: "EprGauge",
        summary: "Setting and confirming thrust — engine pressure ratio and turbine-discharge/jet-pipe pressure tell the crew how hard the engine is working.",
        points: [P("Engine pressure ratio", "EPR is a primary thrust-setting parameter on many engines."), P("Turbine discharge / jet pipe pressure", "Alternative measures of thrust output."), P("N1 as thrust set", "Fan-speed (N1) is the thrust reference on many modern engines.")] },
      { id: "4.3", n: 3, title: "Oil Pressure & Fuel Flow Indication", method: "Fluids", visual: "OilFuelGauge",
        summary: "The lifeblood gauges — oil pressure and temperature and fuel flow reveal engine health and economy at a glance.",
        points: [P("Oil pressure & temperature", "Confirm lubrication and cooling of bearings and gears."), P("Fuel flow", "Shows consumption and helps detect abnormal operation."), P("Cross-checking", "Fluid gauges corroborate the primary engine parameters.")] },
      { id: "4.4", n: 4, title: "Indicating Systems Integration", method: "Instruments", visual: "EngineGaugeCluster",
        summary: "The engine display as a system — EICAS/ECAM gather every parameter into one coherent, alerting picture.",
        points: [P("Integrated engine displays", "EICAS/ECAM present all parameters with limits and alerts."), P("Alerting & exceedance", "Colour bands and messages flag limits and trends."), P("Crew interpretation", "The display supports thrust setting and fault diagnosis.")] },
      { id: "4.5", n: 5, title: "Engine Speed Measurement", method: "Speed", visual: "SpeedGauge",
        summary: "Counting spool speed — N1, N2 (and N3) as percentages, sensed by tacho-generators or phonic wheels.",
        points: [P("N1/N2 speeds", "Each spool's speed is shown as a percentage of a datum."), P("Speed sensing", "Tacho-generators and phonic-wheel/probe sensors measure RPM."), P("Overspeed protection", "Limits and protections guard against destructive overspeed.")] },
      { id: "4.6", n: 6, title: "Vibration Monitoring Systems", method: "Vibration", visual: "VibMonitor",
        summary: "Feeling the engine's health — accelerometers detect imbalance and impending failure before it becomes damage.",
        points: [P("Why monitor vibration", "Rising vibration signals imbalance, damage or bearing wear."), P("Sensors", "Accelerometers on the cases feed a vibration monitor."), P("Interpreting levels", "Trends and thresholds trigger inspection or balancing.")] },
      { id: "4.7", n: 7, title: "Torque & Power Indication", method: "Power", visual: "TorqueGauge",
        summary: "For shaft engines — torque (and torque × RPM) gives the power a turboprop or turboshaft is delivering.",
        points: [P("Torque measurement", "Torquemeters sense shaft twist to indicate power."), P("Shaft horsepower", "Torque and RPM together give delivered power."), P("Use in operation", "Torque is the primary power set for turboprops/turboshafts.")] },
      { id: "4.8", n: 8, title: "Power Augmentation Overview", method: "Augmentation", visual: "AugmentOverview",
        summary: "Getting more thrust when needed — the two families of augmentation: mass-flow boosting (injection) and afterburning.",
        points: [P("Why augment thrust", "Hot/high take-off or combat needs thrust beyond the dry rating."), P("Injection vs afterburning", "Injection cools/boosts mass flow; afterburning adds heat downstream."), P("Trade-offs", "Augmentation costs fuel, complexity and life.")] },
      { id: "4.9", n: 9, title: "Water Injection Systems", method: "Augmentation", visual: "WaterInjection",
        summary: "Cooling the air to boost mass flow — water injected at the inlet or combustor restores take-off thrust on hot days.",
        points: [P("Principle", "Water increases air density/mass flow, raising thrust."), P("Where injected", "At the compressor inlet or into the combustor/diffuser."), P("Limitations", "Water supply and duration limit its use.")] },
      { id: "4.10", n: 10, title: "Water-Methanol Injection", method: "Augmentation", visual: "WaterInjection",
        summary: "Adding methanol to the water — antifreeze plus extra fuel energy that further restores hot-and-high take-off thrust.",
        points: [P("Water-methanol mix", "Methanol prevents freezing and adds combustible energy."), P("Thrust restoration", "Recovers thrust lost to high ambient temperature."), P("System considerations", "Metering and quantity are managed for the take-off run.")] },
      { id: "4.11", n: 11, title: "Afterburner Systems", method: "Augmentation", visual: "Afterburner",
        summary: "Reheat — burning extra fuel in the jet pipe for a large, thirsty boost in thrust, with a variable nozzle to match.",
        points: [P("Afterburning principle", "Fuel is burned in the exhaust's spare oxygen for extra thrust."), P("Components", "Spray bars, flame holders and a variable-area nozzle."), P("Cost", "Very high fuel burn — used briefly for take-off, climb or combat.")] },
      { id: "4.12", n: 12, title: "Unit Assessment & Discussion", method: "Assessment", visual: "EngineGaugeCluster",
        summary: "Consolidating Unit IV — reading a full instrument set and reasoning about augmentation choices.",
        points: [P("Instrument interpretation", "Diagnose condition from a gauge set."), P("Augmentation reasoning", "Choose the right augmentation for a scenario."), P("Self-assessment", "Confirm mastery of indication and augmentation.")] },
    ],
  },

  /* ═══════════════════════ UNIT V ═══════════════════════ */
  {
    id: 5, code: "V", title: "Monitoring & Ground Operation", accent: "#14b8a6", accent2: "#5eead4",
    tag: "Keep it flying", icon: "✦",
    blurb: "Keeping engines healthy in service — condition and trend monitoring, oil and vibration analysis, borescope inspection, cleaning and safe ground running.",
    objectives: [
      "Explain engine condition and trend monitoring",
      "Describe oil-analysis and vibration monitoring",
      "Perform and interpret borescope inspection",
      "State engine inspection standards and cleaning practices",
      "Apply ground-running safety and troubleshooting",
    ],
    sessions: [
      { id: "5.1", n: 1, title: "Engine Health Monitoring Overview", method: "Monitoring", visual: "HealthOverview",
        summary: "The philosophy of on-condition maintenance — watching parameters over time to catch problems before they become failures.",
        points: [P("On-condition maintenance", "Engines are maintained on evidence, not just fixed intervals."), P("Data sources", "Flight data, oil, vibration and borescope build the health picture."), P("Goal", "Predict and prevent — maximise reliability and life.")] },
      { id: "5.2", n: 2, title: "Ground Running & Engine Testing", method: "Ground ops", visual: "GroundRun",
        summary: "Running the engine on the ground — from idle checks to full-power runs and test-cell performance verification.",
        points: [P("Purpose of ground runs", "Verify performance, checks after maintenance, and leak/vibration surveys."), P("Test cell", "Instrumented cells measure thrust and full performance."), P("Procedures", "Warm-up, stabilise, record, cool-down and shut-down.")] },
      { id: "5.3", n: 3, title: "Engine Troubleshooting", method: "Troubleshooting", visual: "Troubleshoot",
        summary: "From symptom to cause — a structured approach to diagnosing engine faults using indications and history.",
        points: [P("Structured diagnosis", "Symptom → possible causes → tests → confirmed fault."), P("Using indications", "Gauges, messages and trends localise the problem."), P("Common faults", "Vibration, EGT, oil and start faults and their causes.")] },
      { id: "5.4", n: 4, title: "Ground Operation Safety", method: "Safety", visual: "SafetyZones",
        summary: "Protecting people and equipment — intake ingestion and exhaust-blast zones, hearing protection and FOD discipline.",
        points: [P("Danger zones", "Intake suction and exhaust blast hazards around a running engine."), P("Personal safety", "Hearing protection, clearances and communication."), P("FOD & housekeeping", "Keeping the ramp clear protects the engine and people.")] },
      { id: "5.5", n: 5, title: "Trend Monitoring Fundamentals", method: "Trends", visual: "TrendMonitor",
        summary: "Reading drift — plotting EGT margin, fuel flow and spool speeds over time to spot slow degradation.",
        points: [P("What is trend monitoring", "Tracking key parameters over many flights to see drift."), P("EGT margin", "A shrinking EGT margin signals hot-section deterioration."), P("Acting on trends", "Shifts trigger washing, inspection or removal planning.")] },
      { id: "5.6", n: 6, title: "Oil Analysis Monitoring", method: "Oil", visual: "OilAnalysis",
        summary: "Reading the oil — magnetic chip detectors and spectrometric oil analysis reveal wear metals from bearings and gears.",
        points: [P("Chip detection", "Magnetic plugs capture metallic debris for inspection."), P("Spectrometric oil analysis", "SOAP quantifies wear-metal concentrations."), P("Interpretation", "Rising metals point to a specific wearing component.")] },
      { id: "5.7", n: 7, title: "Vibration Monitoring", method: "Vibration", visual: "VibMonitor",
        summary: "Tracking vibration in service — using spectra and trends to distinguish fan imbalance from bearing or blade problems.",
        points: [P("In-service vibration", "Broadband and tracked-order vibration are monitored."), P("Diagnosis", "Frequency content localises the source (fan, spool, bearing)."), P("Balancing", "Trim balancing restores smooth running.")] },
      { id: "5.8", n: 8, title: "Borescope Inspection", method: "Inspection", visual: "Borescope",
        summary: "Looking inside without teardown — a flexible borescope inspects compressor, combustor and turbine through access ports.",
        points: [P("What borescoping finds", "Cracks, burning, erosion, FOD and coating loss internally."), P("Access & technique", "Ports and turning tools allow blade-by-blade inspection."), P("Recording defects", "Findings are measured against limits and logged.")] },
      { id: "5.9", n: 9, title: "Engine Inspection Standards", method: "Standards", visual: "InspectionStandards",
        summary: "The rulebook — how manufacturer and regulatory limits define serviceable, repairable and reject conditions.",
        points: [P("Limits & criteria", "Manuals define allowable damage and wear limits."), P("Serviceable vs reject", "Findings are judged against defined thresholds."), P("Documentation", "Inspections and dispositions are recorded for airworthiness.")] },
      { id: "5.10", n: 10, title: "Compressor Washing & Cleaning", method: "Cleaning", visual: "CompressorWash",
        summary: "Restoring lost performance — water washing removes salt and dirt fouling that erodes compressor efficiency.",
        points: [P("Why wash", "Fouling reduces mass flow, efficiency and EGT margin."), P("Wash methods", "On-line and off-line/crank washes clean the compressor."), P("Benefits", "Recovered performance, fuel savings and lower EGT.")] },
      { id: "5.11", n: 11, title: "Foreign Object Damage (FOD)", method: "FOD", visual: "Fod",
        summary: "The ever-present threat — birds, ice, debris and tools that damage blades, and the discipline that prevents it.",
        points: [P("Sources of FOD", "Ramp debris, birds, ice and misplaced tools/hardware."), P("Effects", "Nicks, dents and blade loss degrade or destroy performance."), P("Prevention", "FOD walks, inlet covers and tool control.")] },
      { id: "5.12", n: 12, title: "Unit Assessment & Discussion", method: "Assessment", visual: "HealthOverview",
        summary: "Consolidating Unit V — diagnosing engine health from combined evidence and confirming monitoring mastery.",
        points: [P("Evidence integration", "Combine trend, oil, vibration and borescope findings."), P("Decision making", "Wash, inspect, repair or remove."), P("Self-assessment", "Confirm mastery of monitoring and ground operation.")] },
    ],
  },
];

export const ALL_SESSIONS = UNITS.flatMap((u) =>
  u.sessions.map((s) => ({ ...s, unit: u.id, unitCode: u.code, unitTitle: u.title, accent: u.accent, accent2: u.accent2 }))
);
export const SESSION_COUNT = ALL_SESSIONS.length; // 60
