// Central registry for every module in the ARGUS suite.
// The heavy interactive apps live in /public and are linked to directly.
// `svg` holds the inner markup of a 24x24 stroked icon.

export const GROUPS = [
  { id: "live", label: "Live Ops", blurb: "Real-time data streams" },
  { id: "eng", label: "Engineering", blurb: "Simulation & design labs" },
  { id: "careers", label: "Careers", blurb: "Where it takes you" },
  { id: "academy", label: "Academy", blurb: "Notes & study" },
  { id: "research", label: "Research", blurb: "Deep work" },
  { id: "dash", label: "Dashboards", blurb: "Cohort attendance" },
];

export const MODULES = [
  // ── Live Ops ──
  {
    id: "odyssey",
    name: "Odyssey",
    tag: "Flight ops · gate-to-gate",
    desc: "Full flight-operations console — dispatch, fuel, gate-to-gate timeline.",
    file: "/odyssey.html",
    color: "#f0b64a",
    group: "live",
    live: true,
    svg: '<path d="M2.5 14.6 21.5 9.2"/><path d="M6.6 13.4 4.2 9.9l1.9-.5 3.3 2.5"/><path d="M9.8 19.3 8.1 16.2"/><path d="M3.5 20.5h7"/><circle cx="18.6" cy="10" r="1"/>',
  },
  {
    id: "argus",
    name: "Argus",
    tag: "Live · global radar",
    desc: "The all-seeing radar — live aircraft tracking streamed worldwide.",
    file: "/argus.html",
    color: "#2ec4b6",
    group: "live",
    live: true,
    svg: '<path d="M2 12s3.5-6.5 10-6.5S22 12 22 12s-3.5 6.5-10 6.5S2 12 2 12z"/><circle cx="12" cy="12" r="3"/>',
  },
  {
    id: "oracle",
    name: "Oracle",
    tag: "Orbital · live satellites",
    desc: "Orbital tracker — live satellite passes and ground tracks.",
    file: "/oracle.html",
    color: "#4de1d6",
    group: "live",
    live: true,
    svg: '<circle cx="12" cy="12" r="5.6"/><path d="M12 6.4c-2.1 1.7-2.1 9.5 0 11.2M12 6.4c2.1 1.7 2.1 9.5 0 11.2"/><path d="M6.4 12h11.2"/><ellipse cx="12" cy="12" rx="10.4" ry="4" transform="rotate(-27 12 12)"/><circle cx="20.6" cy="8.9" r="1"/>',
  },
  {
    id: "pyrgos",
    name: "Pyrgos",
    tag: "ATC · tower control",
    desc: "Air-traffic-control radar simulator — vector arrivals onto final, clear departures, real airport geometry.",
    file: "/pyrgos",
    color: "#ffb454",
    group: "live",
    live: true,
    svg: '<path d="M7 21h10"/><path d="M9.5 21V10h5v11"/><path d="M8.6 10 12 5.6 15.4 10"/><path d="M12 5.6V2.8"/><path d="M4.5 14.5 7 13.5M19.5 14.5 17 13.5"/>',
  },

  // ── Engineering ──
  {
    id: "cutaway",
    name: "Cutaway",
    tag: "3D · systems",
    desc: "Interactive 3-D aircraft cutaway explorer + flight simulator.",
    file: "/aircraft-cutaway-explorer.html",
    color: "#22d3ee",
    group: "eng",
    svg: '<path d="M21 16v-2l-8-5V3.6a1.6 1.6 0 0 0-3.2 0V9l-8 5v2l8-2.4V19l-2.2 1.5V22l3.8-1.1L15 22v-1.5L12.8 19v-4.6z"/>',
  },
  {
    id: "windtunnel",
    name: "Wind Tunnel",
    tag: "Aerodynamics",
    desc: "Subsonic, transonic & supersonic aerodynamics simulator.",
    file: "/wind-tunnel-simulator.html",
    color: "#ff5a63",
    group: "eng",
    svg: '<path d="M3 8h11a2.4 2.4 0 1 0-2.4-2.4"/><path d="M3 12h16a2.4 2.4 0 1 1-2.4 2.4"/><path d="M3 16h8.5a2 2 0 1 1-2 2"/>',
  },
  {
    id: "catia",
    name: "CATIA V5",
    tag: "CAD · drafting",
    desc: "Technical drawing lab — CATIA V5 drafting exercises.",
    file: "/technical-drawing-lab.html",
    color: "#5b8def",
    group: "eng",
    svg: '<path d="M4 7.5 12 3l8 4.5v9L12 21l-8-4.5z"/><path d="M4 7.5 12 12l8-4.5M12 12v9"/>',
  },
  {
    id: "ndt",
    name: "NDT Bay",
    tag: "Non-destructive testing",
    desc: "Inspection bay — dye-penetrant, ultrasonic & radiographic NDT.",
    file: "/ndt-inspection-bay.html",
    color: "#f59e0b",
    group: "eng",
    svg: '<circle cx="11" cy="11" r="6.2"/><path d="M20 20l-3.8-3.8"/><path d="M8 11h1.5l1-2.6 1.7 4.8 1.1-2.2H15"/>',
  },
  {
    id: "hangar",
    name: "Hangar",
    tag: "Maintenance",
    desc: "Virtual maintenance hangar — line & base maintenance tasks.",
    file: "/aircraft-maintenance-hangar.html",
    color: "#31c56a",
    group: "eng",
    svg: '<path d="M3 20.5V11l9-6 9 6v9.5"/><path d="M2 20.5h20"/><path d="M8.5 20.5v-5.5h7v5.5"/><path d="M12 8.8v2.4"/>',
  },

  // ── Careers ──
  {
    id: "ascent",
    name: "Ascent",
    tag: "Careers · aviation jobs",
    desc: "Aviation careers board — roles, employers and pathways.",
    file: "/ascent.html",
    color: "#ff9e64",
    group: "careers",
    svg: '<path d="M3 20.5h18"/><path d="M6.5 20.5V13"/><path d="M11.5 20.5V9"/><path d="M16.5 20.5V5"/><path d="M14 3h6v6"/><path d="M20 3 12.5 10.5"/>',
  },

  // ── Academy ──
  {
    id: "ground-school",
    name: "Ground School",
    tag: "Notes · study library",
    desc: "Course notes and materials organised by subject — upload as instructor, browse and download as a student.",
    file: "/ground-school",
    color: "#4a9eff",
    group: "academy",
    svg: '<path d="M12 3 2 8l10 5 10-5-10-5z"/><path d="M6 10.5V16c0 1.6 2.7 3 6 3s6-1.4 6-3v-5.5"/><path d="M22 8v6"/>',
  },

  // ── Research ──
  {
    id: "halcyon",
    name: "Halcyon",
    tag: "MSc dissertation",
    desc: "Control of a fixed-wing multibody UAV — MSc dissertation lab.",
    file: "/halcyon.html",
    color: "#8b93ff",
    group: "research",
    svg: '<path d="M3 12c3-5 6-5 9 0s6 5 9 0"/><path d="M3 17c3-5 6-5 9 0s6 5 9 0"/>',
  },
  {
    id: "gargantua",
    name: "Gargantua",
    tag: "Relativity · raytracer",
    desc: "GPU black-hole raytracer — gravitational lensing in real time.",
    file: "/gargantua/index.html",
    color: "#b98cff",
    group: "research",
    svg: '<circle cx="12" cy="12" r="4.1"/><circle cx="12" cy="12" r="6.6"/><ellipse cx="12" cy="12" rx="10.6" ry="3.1" transform="rotate(-18 12 12)"/><path d="M2.4 8.6c2.6 1.5 6 2.3 9.6 2.3s7-.8 9.6-2.3"/>',
  },

  // ── Dashboards ──
  {
    id: "argus-dash",
    name: "Attendance",
    tag: "ARGUS · BSc Aero IIA",
    desc: "Attendance dashboard — BSc Aerospace Engineering, cohort IIA.",
    file: "/argus-dashboard.html",
    color: "#f0b64a",
    group: "dash",
    svg: '<circle cx="12" cy="12" r="9"/><path d="M12 3v3M12 18v3M3 12h3M18 12h3"/><circle cx="12" cy="12" r="2.4" fill="currentColor" stroke="none"/>',
  },
  {
    id: "muster",
    name: "Muster",
    tag: "BBA Aviation · IIA",
    desc: "Attendance dashboard — BBA Aviation, cohort IIA.",
    file: "/muster.html",
    color: "#2ec4b6",
    group: "dash",
    svg: '<path d="M4 20v-5M9 20V9M14 20v-8M19 20V5"/>',
  },
  {
    id: "olympia",
    name: "Olympia",
    tag: "BBA Aviation · IIIB",
    desc: "Attendance dashboard — BBA Aviation, cohort IIIB.",
    file: "/olympia.html",
    color: "#4de1d6",
    group: "dash",
    svg: '<circle cx="12" cy="8" r="3.4"/><path d="M6 21v-2a4 4 0 0 1 4-4h4a4 4 0 0 1 4 4v2"/>',
  },
  {
    id: "absence",
    name: "Absence Audit",
    tag: "BBA Aviation · IIC",
    desc: "Absence audit report — BBA Aviation, cohort IIC.",
    file: "/absence-audit-report.html",
    color: "#ff9e64",
    group: "dash",
    svg: '<path d="M6 3h9l4 4v14H6z"/><path d="M15 3v4h4"/><path d="M9 12h6M9 16h4"/>',
  },
  {
    id: "mentor",
    name: "Mentor",
    tag: "Mentee console · locked",
    desc: "Mentee console — private mentor dashboard.",
    file: "/mentor.html",
    color: "#4a9eff",
    group: "dash",
    locked: true,
    svg: '<path d="M3 3v18h18"/><path d="M7 14l3-4 3 3 4-6"/><circle cx="20" cy="7" r="1.6" fill="currentColor" stroke="none"/>',
  },
];
